# Generated by Django 6.0.7 on 2026-07-19 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "verbose_name": "item",
                "verbose_name_plural": "items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["name"], name="item_name_idx"),
                    models.Index(fields=["is_active"], name="item_is_active_idx"),
                    models.Index(fields=["created_at"], name="item_created_at_idx"),
                ],
            },
        ),
    ]
