# Generated by Django 6.0.7 on 2026-07-26 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_instructor_alter_item_id_reservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructor",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/"),
        ),
    ]
