# Generated by Django 6.0.7 on 2026-07-26 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_instructor_photo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="item",
            name="item_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="item_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="item",
            name="item_created_at_idx",
        ),
        migrations.DeleteModel(
            name="Item",
        ),
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["reservation_date"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="instructor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="core.instructor",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("user", "instructor", "reservation_date"),
                name="unique_user_instructor_reservation",
            ),
        ),
    ]
