# Generated by Django 6.0.7 on 2026-07-27 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_item_item_name_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="available_dates",
                        to="core.instructor",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("instructor", "date"),
                        name="unique_instructor_available_date",
                    )
                ],
            },
        ),
    ]
