from django.db import models


class Item(models.Model):
    """
    Generic item model for the application.

    This model serves as a foundational entity that can be extended
    or renamed based on future domain requirements.
    """

    # Primary identifier for the item, auto-generated by Django
    id = models.BigAutoField(primary_key=True)

    # Human-readable name for the item, limited to 200 characters
    # Indexed for faster search and filter operations
    name = models.CharField(max_length=200, db_index=True)

    # Optional detailed description of the item
    # Can be left blank, defaults to empty string
    description = models.TextField(blank=True, default="")

    # Timestamp of when the item was created
    # Automatically set on first save, indexed for ordering by date
    created_at = models.DateTimeField(auto_now_add=True, db_index=True)

    # Timestamp of when the item was last modified
    # Automatically updated on every save
    updated_at = models.DateTimeField(auto_now=True)

    # Soft delete flag to mark items as inactive without deleting them
    # Indexed for faster filtering of active items
    is_active = models.BooleanField(default=True, db_index=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "item"
        verbose_name_plural = "items"
        indexes = [
            models.Index(fields=["name"], name="item_name_idx"),
            models.Index(fields=["is_active"], name="item_is_active_idx"),
            models.Index(fields=["created_at"], name="item_created_at_idx"),
        ]

    def __str__(self):
        """Return the human-readable string representation of the item."""
        return self.name
